import type { Metadata } from "next";
import "./globals.css";
import SmoothScroll from "./components/SmoothScroll";
import { PreloadProvider } from "./components/PreloadProvider";
import Loader from "./components/Loader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SmoothScroll>
          <PreloadProvider totalAssets={5}>
            <Loader />
            {children}
          </PreloadProvider>
        </SmoothScroll>
      </body>
    </html>
  );
}
